# Generated by Django 3.1.5 on 2021-01-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makerCommission', models.FloatField()),
                ('takerCommission', models.FloatField()),
                ('buyerCommission', models.FloatField()),
                ('sellerCommission', models.FloatField()),
                ('canTrade', models.BooleanField()),
                ('canWithdraw', models.BooleanField()),
                ('canDeposit', models.BooleanField()),
                ('updateTime', models.PositiveBigIntegerField()),
                ('accountType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('free', models.FloatField()),
                ('locked', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='main.account')),
            ],
        ),
    ]
