# Generated by Django 3.1.5 on 2021-01-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='buyerCommission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='canDeposit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='canTrade',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='canWithdraw',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='makerCommission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='sellerCommission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='takerCommission',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='updateTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='main.account'),
        ),
    ]
