# Generated by Django 3.1.5 on 2021-01-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_getaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=6)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
